# Generated by Django 5.0.11 on 2025-02-04 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='created_by_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_team_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
