# Generated by Django 5.0.11 on 2025-02-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_teamtask_created_by_management_teamtask_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtask',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_team_tasks', to='employees.manager'),
        ),
    ]
