# Generated by Django 5.0.12 on 2025-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_teamrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='time',
            field=models.TimeField(blank=True, help_text='Time for this request (optional)', null=True),
        ),
    ]
