# Generated by Django 5.0.12 on 2025-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_teamrequest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='check_in',
            field=models.BooleanField(default=False, help_text='Request for check-in'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Requested check-in time', null=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='check_out',
            field=models.BooleanField(default=False, help_text='Request for check-out'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Requested check-out time', null=True),
        ),
    ]
