# Generated by Django 5.0.12 on 2025-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_remove_teamrequest_time_teamrequest_check_in_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("WORKING", "Working Day"),
                            ("HOLIDAY", "Holiday"),
                            ("FESTIVAL", "Festival"),
                            ("SPECIAL_WORKING", "Special Working Day"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        default="WORKING",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "is_saturday_working",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this Saturday is a working day",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Calendar Day",
                "verbose_name_plural": "Calendar Days",
                "ordering": ["date"],
            },
        ),
    ]
